version: '3'
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert-key:/etc/nginx/ssl
  php-fpm:
    build: ./php-fpm
    depends_on:
      - mysql
    ports:
      - 9000:9000
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=gizhack
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=gizmohack
    volumes:
      - ./data-mysql:/var/lib/mysql
    container_name: mysql57
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    depends_on:
      - nginx
    privileged: true
    container_name: selenium