version: '3'
services: 
  nginx:
    image: nginx:alpine
    depends_on: 
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert-key:/etc/nginx/ssl
  php-fpm:
    build: ./php-fpm
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www/html
